---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: division-deploy
  labels:
    app: divisioncalc
spec:
  replicas: 2
  selector:
    matchLabels:
      app: divisioncalc
  template:
    metadata:
      labels:
        app: divisioncalc
    spec:
      containers:
        - name: divisioncalc
          image: santi10/division:1
          ports:
            - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: division-svc
spec:
  type: ClusterIP
  selector:
    app: divisioncalc
  ports:
    - port: 80
      targetPort: 5000
