---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: metrics-deploy
  labels:
    app: metricscalc
spec:
  replicas: 2
  selector:
    matchLabels:
      app: metricscalc
  template:
    metadata:
      labels:
        app: metricscalc
    spec:
      containers:
        - name: metricscalc
          image: santi10/metrics:1
          ports:
            - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: metrics-svc
spec:
  type: ClusterIP 
  selector:
    app: metricscalc
  ports:
    - port: 80
      targetPort: 5000
