---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: random-deploy
  labels:
    app: randomcalc
spec:
  replicas: 2
  selector:
    matchLabels:
      app: randomcalc
  template:
    metadata:
      labels:
        app: randomcalc
    spec:
      containers:
        - name: randomcalc
          image: santi10/random:1
          ports:
            - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: random-svc
spec:
  type: ClusterIP
  selector:
    app: randomcalc
  ports:
    - port: 80
      targetPort: 5000
